receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: 
            - http://localhost:8081/
        #     # Origins can have wildcards with *, use * by itself to match any origin.
        #     # - https://*.example.com
        # headers:
        #   - Access-Control-Allow-Origin:'*'

processors:
  batch:

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]